# Generated by Django 4.1.3 on 2023-04-28 07:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(default=True, upload_to='image')),
                ('shape', models.CharField(choices=[('circle', 'circle'), ('rectangle', 'rectangle'), ('oval', 'oval'), ('square', 'square')], default='circle', max_length=40)),
                ('layers', models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three')], default='one', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=240)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cakes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='order-placed', max_length=200)),
                ('expected_deliverydate', models.DateField(default=datetime.date(2023, 4, 30))),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cakes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in-cart', 'in-cart'), ('order-placed', 'order-placed'), ('order-cancelled', 'order-cancelled')], default='in-cart', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cakes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
