# Generated by Django 4.1.3 on 2023-05-02 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 5, 4)),
        ),
    ]
